[package]
name = "update-homebrew-tap-playground"
version = "0.1.16"
edition = "2024"

[[bin]]
name = "greet"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
clap_complete = "4.5"
