name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Generate artefact
      run: |
        mkdir -p ./tmp
        echo "Some artefact generated at $(date)" > ./tmp/description.txt
    - name: Cache
      if: github.ref_type == 'tag'
      id: cache-description-file
      uses: actions/cache@v4
      with:
        path: ./tmp
        key: ${{ runner.os }}-description-file-${{ github.sha }}

  release-draft:
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    env:
      RELEASE_NAME: ${{ github.ref_name }}
    steps:
      - name: Restore cached description file
        id: cache-description-file-restore
        uses: actions/cache/restore@v4
        with:
          path: ./tmp
          key: ${{ runner.os }}-description-file-${{ github.sha }}
      - name: Create a release draft if it doesn't exist
        run: |
          RELEASE_NAME=${{ env.RELEASE_NAME }}
          gh release view $RELEASE_NAME > /dev/null 2>&1
          if [[ "$(gh release view $RELEASE_NAME 2>&1)" == "release not found" ]]; then
            echo "Release not found. Creating release draft..."
            gh release create $RELEASE_NAME --draft --title "$RELEASE_NAME"
            echo "release-exists=false" >> $GITHUB_OUTPUT
            echo "release-created=true" >> $GITHUB_OUTPUT
          else
            echo "Release found."
            echo "release-exists=true" >> $GITHUB_OUTPUT
            echo "release-created=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload description file
        run: |
          gh release upload ${{ env.RELEASE_NAME }} ./tmp/description.txt
