name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ minimal required for pushing commits

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
      - name: Update Homebrew Formula
        uses: topheman/update-homebrew-tap@master
        with:
          formula-target-repository: topheman/homebrew-test-tap
          formula-target-file: Formula/greet.rb
          tar-files: |
            {
              "linuxArm": "https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-aarch64-unknown-linux-gnu.tar.gz",
              "linuxIntel": "https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-x86_64-unknown-linux-gnu.tar.gz",
              "macArm": "https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-aarch64-apple-darwin.tar.gz",
              "macIntel": "https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-x86_64-apple-darwin.tar.gz"
            }
          metadata: |
            {
              "version": "${{ github.ref_name }}",
              "binaryName": "greet",
              "description": "Greet CLI application",
              "homepage": "https://github.com/topheman/update-homebrew-tap-playground",
              "license": "MIT"
            }
          github-token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
