name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ minimal required for pushing commits

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
      - name: Update Homebrew Formula
        uses: topheman/update-homebrew-tap@master
        with:
          formula-target-repository: topheman/test-homebrew-tap
          formula-target-file: Formula/greet.rb
          formula-template: homebrew/formula.rb.ejs
          tar-files: |
            linux-intel=https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-x86_64-unknown-linux-gnu.tar.gz
            mac-arm=https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-aarch64-apple-darwin.tar.gz
            mac-intel=https://github.com/topheman/update-homebrew-tap-playground/releases/download/${{ github.ref_name }}/greet-x86_64-apple-darwin.tar.gz
          metadata: |
            version=${{ github.ref_name }}
